version: '3.7'

services: 
  
  # Back-end API
  smart-brain-api: 
    container_name: backend
    build: ./  # use Dockerfile
    command: yarn start
    working_dir: /usr/src/smart-brain-api
    ports:
      - "3000:3000"
    environment:
      POSTGRES_URI: postgres://tacotruffles:secret@postgres:5432/smart-brain-docker
      REDIS_URI: redis://redis:6379
      CLARIFAI_API_KEY: 028f69d843ad4c36b4898fc1978509ab
      JWT_SECRET: "hansololoveschewie"
    links:
      - postgres
      - redis
    volumes:
      - ./:/usr/src/smart-brain-api

  # Postgres
  postgres:
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: smart-brain-docker
      POSTGRES_USER: tacotruffles
      POSTGRES_PASSWORD: secret
    # container_name: postgres
    build: ./postgres
    ports:
      - "5432:5432"

  # Redis
  redis:
    container_name: redis-server
    build: ./redis
    ports: 
      - "6379:6379"