version: '3.7'

services: 
  smart-brain-api: 
    container_name: backend
    # image: node:8.11.3
    build: ./
    command: yarn start
    working_dir: /usr/src/smart-brain-api
    ports:
      - "3000:3000"
    # environment:
    # link: